#pragma once

#include <windows.h>
#include <math.h>

namespace D3D9
{
#undef DIRECT3D_VERSION
#define DIRECT3D_VERSION         0x0900
#undef D3DCOLOR_DEFINED
#undef D3DCOLORVALUE_DEFINED
#undef D3DVECTOR_DEFINED
#undef D3DRECT_DEFINED
#undef D3DMATRIX_DEFINED

#undef D3DFVF_POSITION_MASK
#undef D3DFVF_RESERVED2
#undef D3DERR_WRONGTEXTUREFORMAT 
#undef D3DERR_UNSUPPORTEDCOLOROPERATION 
#undef D3DERR_UNSUPPORTEDCOLORARG
#undef D3DERR_UNSUPPORTEDALPHAOPERATION 
#undef D3DERR_UNSUPPORTEDALPHAARG
#undef D3DERR_TOOMANYOPERATIONS 
#undef D3DERR_CONFLICTINGTEXTUREFILTER 
#undef D3DERR_UNSUPPORTEDFACTORVALUE 
#undef D3DERR_CONFLICTINGRENDERSTATE 
#undef D3DERR_UNSUPPORTEDTEXTUREFILTER 
#undef D3DERR_CONFLICTINGTEXTUREPALETTE 
#undef D3D_OK

#include <d3d9.h>
#include <d3dx9.h>

#undef D3DFVF_POSITION_MASK
#undef D3DFVF_RESERVED2
#undef D3DERR_WRONGTEXTUREFORMAT 
#undef D3DERR_UNSUPPORTEDCOLOROPERATION 
#undef D3DERR_UNSUPPORTEDCOLORARG
#undef D3DERR_UNSUPPORTEDALPHAOPERATION 
#undef D3DERR_UNSUPPORTEDALPHAARG
#undef D3DERR_TOOMANYOPERATIONS 
#undef D3DERR_CONFLICTINGTEXTUREFILTER 
#undef D3DERR_UNSUPPORTEDFACTORVALUE 
#undef D3DERR_CONFLICTINGRENDERSTATE 
#undef D3DERR_UNSUPPORTEDTEXTUREFILTER 
#undef D3DERR_CONFLICTINGTEXTUREPALETTE 
#undef D3D_OK


CONST DWORD D3DFVF_POSITION_MASK = 0x400E;
CONST DWORD D3DFVF_RESERVED2 = 0x6000;

CONST HRESULT D3DERR_WRONGTEXTUREFORMAT = MAKE_D3DHRESULT(2072);
CONST HRESULT D3DERR_UNSUPPORTEDCOLOROPERATION = MAKE_D3DHRESULT(2073);
CONST HRESULT D3DERR_UNSUPPORTEDCOLORARG = MAKE_D3DHRESULT(2074);
CONST HRESULT D3DERR_UNSUPPORTEDALPHAOPERATION = MAKE_D3DHRESULT(2075);
CONST HRESULT D3DERR_UNSUPPORTEDALPHAARG = MAKE_D3DHRESULT(2076);
CONST HRESULT D3DERR_TOOMANYOPERATIONS = MAKE_D3DHRESULT(2077);
CONST HRESULT D3DERR_CONFLICTINGTEXTUREFILTER = MAKE_D3DHRESULT(2078);
CONST HRESULT D3DERR_UNSUPPORTEDFACTORVALUE = MAKE_D3DHRESULT(2079);
CONST HRESULT D3DERR_CONFLICTINGRENDERSTATE = MAKE_D3DHRESULT(2081);
CONST HRESULT D3DERR_UNSUPPORTEDTEXTUREFILTER = MAKE_D3DHRESULT(2082);
CONST HRESULT D3DERR_CONFLICTINGTEXTUREPALETTE = MAKE_D3DHRESULT(2086);

CONST HRESULT D3D_OK = S_OK;             

#undef DIRECT3D_VERSION
};
