#pragma once

#include "../d3d/d3d_device.h"

#include "d2gi_common.h"


class D2GIDevice : public DeviceProxy, public D2GIBase
{
public:
	D2GIDevice(D2GI*);
	virtual ~D2GIDevice();

	STDMETHOD(EnumTextureFormats)(D3D7::LPD3DENUMPIXELFORMATSCALLBACK, LPVOID);
	STDMETHOD(SetTexture)(DWORD, D3D7::LPDIRECTDRAWSURFACE7);
	STDMETHOD(SetViewport)(D3D7::LPD3DVIEWPORT7);
	STDMETHOD(Clear)(DWORD, D3D7::LPD3DRECT, DWORD, D3D7::D3DCOLOR, D3D7::D3DVALUE, DWORD);
	STDMETHOD(LightEnable)(DWORD, BOOL);
	STDMETHOD(BeginScene)();
	STDMETHOD(EndScene)();
	STDMETHOD(SetRenderState)(D3D7::D3DRENDERSTATETYPE, DWORD);
	STDMETHOD(SetTextureStageState)(DWORD, D3D7::D3DTEXTURESTAGESTATETYPE, DWORD);
	STDMETHOD(ValidateDevice)(LPDWORD);
	STDMETHOD(SetTransform)(D3D7::D3DTRANSFORMSTATETYPE, D3D7::LPD3DMATRIX);
	STDMETHOD(SetLight)(DWORD, D3D7::LPD3DLIGHT7);
	STDMETHOD(SetMaterial)(D3D7::LPD3DMATERIAL7);
	STDMETHOD(SetClipStatus)(D3D7::LPD3DCLIPSTATUS);
};
