#if 0
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /T ps_3_0 /Vn g_pBlitterPS /Fh
//    E:\Users\Admin\Documents\Visual_Studio_2008\Projects\D2GI\D2GI\src\d2gi\d2gi_blitter_ps.h
//    E:\Users\Admin\Documents\Visual_Studio_2008\Projects\D2GI\D2GI\src\d2gi\d2gi_blitter_ps.hlsl
//
//
// Parameters:
//
//   sampler2D g_txSourceTexture;
//   float4 g_vBorder;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   g_vBorder         c0       1
//   g_txSourceTexture s0       1
//

    ps_3_0
    dcl_texcoord v0.xy
    dcl_2d s0
    max r0.xy, v0, c0
    min r1.xy, c0.zwzw, r0
    texld oC0, r1, s0

// approximately 3 instruction slots used (1 texture, 2 arithmetic)
#endif

const BYTE g_pBlitterPS[] =
{
      0,   3, 255, 255, 254, 255, 
     48,   0,  67,  84,  65,  66, 
     28,   0,   0,   0, 139,   0, 
      0,   0,   0,   3, 255, 255, 
      2,   0,   0,   0,  28,   0, 
      0,   0,   0,   1,   0,   0, 
    132,   0,   0,   0,  68,   0, 
      0,   0,   3,   0,   0,   0, 
      1,   0,   2,   0,  88,   0, 
      0,   0,   0,   0,   0,   0, 
    104,   0,   0,   0,   2,   0, 
      0,   0,   1,   0,   2,   0, 
    116,   0,   0,   0,   0,   0, 
      0,   0, 103,  95, 116, 120, 
     83, 111, 117, 114,  99, 101, 
     84, 101, 120, 116, 117, 114, 
    101,   0, 171, 171,   4,   0, 
     12,   0,   1,   0,   1,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0, 103,  95, 118,  66, 
    111, 114, 100, 101, 114,   0, 
    171, 171,   1,   0,   3,   0, 
      1,   0,   4,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
    112, 115,  95,  51,  95,  48, 
      0,  77, 105,  99, 114, 111, 
    115, 111, 102, 116,  32,  40, 
     82,  41,  32,  72,  76,  83, 
     76,  32,  83, 104,  97, 100, 
    101, 114,  32,  67, 111, 109, 
    112, 105, 108, 101, 114,  32, 
     57,  46,  50,  57,  46,  57, 
     53,  50,  46,  51,  49,  49, 
     49,   0,  31,   0,   0,   2, 
      5,   0,   0, 128,   0,   0, 
      3, 144,  31,   0,   0,   2, 
      0,   0,   0, 144,   0,   8, 
     15, 160,  11,   0,   0,   3, 
      0,   0,   3, 128,   0,   0, 
    228, 144,   0,   0, 228, 160, 
     10,   0,   0,   3,   1,   0, 
      3, 128,   0,   0, 238, 160, 
      0,   0, 228, 128,  66,   0, 
      0,   3,   0,   8,  15, 128, 
      1,   0, 228, 128,   0,   8, 
    228, 160, 255, 255,   0,   0
};
