#pragma once

#include <d3d.h>


class DeviceProxy : public IDirect3DDevice7
{
protected:
	IDirect3DDevice7* m_pOriginal;
public:
	DeviceProxy(IDirect3DDevice7*);
	virtual ~DeviceProxy();

	STDMETHOD(QueryInterface)( REFIID riid, LPVOID* ppvObj);
	STDMETHOD_(ULONG, AddRef)();
	STDMETHOD_(ULONG, Release)();
	STDMETHOD(GetCaps)( LPD3DDEVICEDESC7);
	STDMETHOD(EnumTextureFormats)( LPD3DENUMPIXELFORMATSCALLBACK, LPVOID);
	STDMETHOD(BeginScene)();
	STDMETHOD(EndScene)();
	STDMETHOD(GetDirect3D)( LPDIRECT3D7*);
	STDMETHOD(SetRenderTarget)( LPDIRECTDRAWSURFACE7, DWORD);
	STDMETHOD(GetRenderTarget)( LPDIRECTDRAWSURFACE7*);
	STDMETHOD(Clear)( DWORD, LPD3DRECT, DWORD, D3DCOLOR, D3DVALUE, DWORD);
	STDMETHOD(SetTransform)( D3DTRANSFORMSTATETYPE, LPD3DMATRIX);
	STDMETHOD(GetTransform)( D3DTRANSFORMSTATETYPE, LPD3DMATRIX);
	STDMETHOD(SetViewport)( LPD3DVIEWPORT7);
	STDMETHOD(MultiplyTransform)( D3DTRANSFORMSTATETYPE, LPD3DMATRIX);
	STDMETHOD(GetViewport)( LPD3DVIEWPORT7);
	STDMETHOD(SetMaterial)( LPD3DMATERIAL7);
	STDMETHOD(GetMaterial)( LPD3DMATERIAL7);
	STDMETHOD(SetLight)( DWORD, LPD3DLIGHT7);
	STDMETHOD(GetLight)( DWORD, LPD3DLIGHT7);
	STDMETHOD(SetRenderState)( D3DRENDERSTATETYPE, DWORD);
	STDMETHOD(GetRenderState)( D3DRENDERSTATETYPE, LPDWORD);
	STDMETHOD(BeginStateBlock)();
	STDMETHOD(EndStateBlock)( LPDWORD);
	STDMETHOD(PreLoad)( LPDIRECTDRAWSURFACE7);
	STDMETHOD(DrawPrimitive)( D3DPRIMITIVETYPE, DWORD, LPVOID, DWORD, DWORD);
	STDMETHOD(DrawIndexedPrimitive)( D3DPRIMITIVETYPE, DWORD, LPVOID, DWORD, LPWORD, DWORD, DWORD);
	STDMETHOD(SetClipStatus)( LPD3DCLIPSTATUS);
	STDMETHOD(GetClipStatus)( LPD3DCLIPSTATUS);
	STDMETHOD(DrawPrimitiveStrided)( D3DPRIMITIVETYPE, DWORD, LPD3DDRAWPRIMITIVESTRIDEDDATA, DWORD, DWORD);
	STDMETHOD(DrawIndexedPrimitiveStrided)( D3DPRIMITIVETYPE, DWORD, LPD3DDRAWPRIMITIVESTRIDEDDATA, DWORD, LPWORD, DWORD, DWORD);
	STDMETHOD(DrawPrimitiveVB)( D3DPRIMITIVETYPE, LPDIRECT3DVERTEXBUFFER7, DWORD, DWORD, DWORD);
	STDMETHOD(DrawIndexedPrimitiveVB)( D3DPRIMITIVETYPE, LPDIRECT3DVERTEXBUFFER7, DWORD, DWORD, LPWORD, DWORD, DWORD);
	STDMETHOD(ComputeSphereVisibility)( LPD3DVECTOR, LPD3DVALUE, DWORD, DWORD, LPDWORD);
	STDMETHOD(GetTexture)( DWORD, LPDIRECTDRAWSURFACE7*);
	STDMETHOD(SetTexture)( DWORD, LPDIRECTDRAWSURFACE7);
	STDMETHOD(GetTextureStageState)( DWORD, D3DTEXTURESTAGESTATETYPE, LPDWORD);
	STDMETHOD(SetTextureStageState)( DWORD, D3DTEXTURESTAGESTATETYPE, DWORD);
	STDMETHOD(ValidateDevice)( LPDWORD);
	STDMETHOD(ApplyStateBlock)( DWORD);
	STDMETHOD(CaptureStateBlock)( DWORD);
	STDMETHOD(DeleteStateBlock)( DWORD);
	STDMETHOD(CreateStateBlock)( D3DSTATEBLOCKTYPE, LPDWORD);
	STDMETHOD(Load)( LPDIRECTDRAWSURFACE7, LPPOINT, LPDIRECTDRAWSURFACE7, LPRECT, DWORD);
	STDMETHOD(LightEnable)( DWORD, BOOL);
	STDMETHOD(GetLightEnable)( DWORD, BOOL*);
	STDMETHOD(SetClipPlane)( DWORD, D3DVALUE*);
	STDMETHOD(GetClipPlane)( DWORD, D3DVALUE*);
	STDMETHOD(GetInfo)( DWORD, LPVOID, DWORD);
};