; D2GI configuration file
; Visit D2GI repository page for help: https://github.com/REDPOWAR/D2GI

[VIDEO]
Width       = 0
Height      = 0
WindowMode  = borderless
EnableVSync = 1
FixAlpha    = 1
; Set to a value over 1 to force Anisotropic Filtering. Up to 16x.
AnisotropyLevel = 16
; Multisample Anti-Aliasing level. Allowed values: 0 (off), 2-16, max (maximum supported).
MSAALevel = 0

[HOOKS]
EnableHooks = 1
EnableUIFix = 1
EnableMirrorsFix = 1
; Patch 8.2 forces all threads to a single core, ruining performance.
; Setting this option to 1 reverts this change.
AllCoresAffinity = 1

[SCREENSHOTS]
SavePath = .\\screenshots
; Supported formats - bmp, jpg, png
ImageFormat = jpg

[TEXTUREUVOVERRIDES]
; Textures listed here override their UV addressing beyond what the stock game allows.
; Name format: moduleName.textureName
; Allowed modes: CLAMP, WRAP, MIRROR
; Mostly used to fix 1px-wide seams on trees and other transparent textures when MSAA is enabled.
aq.forest1, CLAMP, WRAP
