[VIDEO]
Width       = 0
Height      = 0
WindowMode  = borderless
EnableVSync = 1
FixAlpha    = 1
; Set to a value over 1 to force Anisotropic Filtering. Up to 16x.
AnisotropyLevel = 16
; Multisample Anti-Aliasing level. Allowed values: 0 (off), 2-16, max (maximum supported).
MSAALevel = 0

[HOOKS]
EnableHooks = 1
EnableUIFix = 1

[SCREENSHOTS]
SavePath = .\\screenshots
; Supported formats - bmp, jpg, png
ImageFormat = jpg
