#pragma once

#include <windows.h>

#include "../d3d7.h"


class SurfaceProxy : public D3D7::IDirectDrawSurface7
{
protected:
	D3D7::IDirectDrawSurface7* m_pOriginal;
public:
	SurfaceProxy(D3D7::IDirectDrawSurface7*);
	virtual ~SurfaceProxy();

	D3D7::IDirectDrawSurface7* GetOriginal() { return m_pOriginal; }

	STDMETHOD(QueryInterface) ( REFIID riid, LPVOID FAR* ppvObj) ;
	STDMETHOD_(ULONG, AddRef) ()  ;
	STDMETHOD_(ULONG, Release) () ;
	STDMETHOD(AddAttachedSurface)(D3D7::LPDIRECTDRAWSURFACE7) ;
	STDMETHOD(AddOverlayDirtyRect)( LPRECT) ;
	STDMETHOD(Blt)( LPRECT, D3D7::LPDIRECTDRAWSURFACE7, LPRECT, DWORD, D3D7::LPDDBLTFX) ;
	STDMETHOD(BltBatch)(D3D7::LPDDBLTBATCH, DWORD, DWORD) ;
	STDMETHOD(BltFast)( DWORD, DWORD, D3D7::LPDIRECTDRAWSURFACE7, LPRECT, DWORD) ;
	STDMETHOD(DeleteAttachedSurface)( DWORD, D3D7::LPDIRECTDRAWSURFACE7) ;
	STDMETHOD(EnumAttachedSurfaces)( LPVOID, D3D7::LPDDENUMSURFACESCALLBACK7) ;
	STDMETHOD(EnumOverlayZOrders)( DWORD, LPVOID, D3D7::LPDDENUMSURFACESCALLBACK7) ;
	STDMETHOD(Flip)(D3D7::LPDIRECTDRAWSURFACE7, DWORD) ;
	STDMETHOD(GetAttachedSurface)(D3D7::LPDDSCAPS2, D3D7::LPDIRECTDRAWSURFACE7 FAR*) ;
	STDMETHOD(GetBltStatus)( DWORD) ;
	STDMETHOD(GetCaps)(D3D7::LPDDSCAPS2) ;
	STDMETHOD(GetClipper)(D3D7::LPDIRECTDRAWCLIPPER FAR*) ;
	STDMETHOD(GetColorKey)( DWORD, D3D7::LPDDCOLORKEY) ;
	STDMETHOD(GetDC)( HDC FAR*) ;
	STDMETHOD(GetFlipStatus)( DWORD) ;
	STDMETHOD(GetOverlayPosition)( LPLONG, LPLONG) ;
	STDMETHOD(GetPalette)(D3D7::LPDIRECTDRAWPALETTE FAR*) ;
	STDMETHOD(GetPixelFormat)(D3D7::LPDDPIXELFORMAT) ;
	STDMETHOD(GetSurfaceDesc)(D3D7::LPDDSURFACEDESC2) ;
	STDMETHOD(Initialize)(D3D7::LPDIRECTDRAW, D3D7::LPDDSURFACEDESC2) ;
	STDMETHOD(IsLost)() ;
	STDMETHOD(Lock)( LPRECT, D3D7::LPDDSURFACEDESC2, DWORD, HANDLE) ;
	STDMETHOD(ReleaseDC)( HDC) ;
	STDMETHOD(Restore)() ;
	STDMETHOD(SetClipper)(D3D7::LPDIRECTDRAWCLIPPER) ;
	STDMETHOD(SetColorKey)( DWORD, D3D7::LPDDCOLORKEY) ;
	STDMETHOD(SetOverlayPosition)( LONG, LONG) ;
	STDMETHOD(SetPalette)(D3D7::LPDIRECTDRAWPALETTE) ;
	STDMETHOD(Unlock)( LPRECT) ;
	STDMETHOD(UpdateOverlay)( LPRECT, D3D7::LPDIRECTDRAWSURFACE7, LPRECT, DWORD, D3D7::LPDDOVERLAYFX) ;
	STDMETHOD(UpdateOverlayDisplay)( DWORD) ;
	STDMETHOD(UpdateOverlayZOrder)( DWORD, D3D7::LPDIRECTDRAWSURFACE7) ;
	STDMETHOD(GetDDInterface)( LPVOID FAR*) ;
	STDMETHOD(PageLock)( DWORD) ;
	STDMETHOD(PageUnlock)( DWORD) ;
	STDMETHOD(SetSurfaceDesc)(D3D7::LPDDSURFACEDESC2, DWORD) ;
	STDMETHOD(SetPrivateData)( REFGUID, LPVOID, DWORD, DWORD) ;
	STDMETHOD(GetPrivateData)( REFGUID, LPVOID, LPDWORD) ;
	STDMETHOD(FreePrivateData)( REFGUID) ;
	STDMETHOD(GetUniquenessValue)( LPDWORD) ;
	STDMETHOD(ChangeUniquenessValue)() ;
	STDMETHOD(SetPriority)( DWORD) ;
	STDMETHOD(GetPriority)( LPDWORD) ;
	STDMETHOD(SetLOD)( DWORD) ;
	STDMETHOD(GetLOD)( LPDWORD) ;
};
