#pragma once

#include <ddraw.h>


class SurfaceProxy : public IDirectDrawSurface7
{
protected:
	IDirectDrawSurface7* m_pOriginal;
public:
	SurfaceProxy(IDirectDrawSurface7*);
	virtual ~SurfaceProxy();

	IDirectDrawSurface7* GetOriginal() { return m_pOriginal; }

	STDMETHOD(QueryInterface) ( REFIID riid, LPVOID FAR* ppvObj) ;
	STDMETHOD_(ULONG, AddRef) ()  ;
	STDMETHOD_(ULONG, Release) () ;
	STDMETHOD(AddAttachedSurface)( LPDIRECTDRAWSURFACE7) ;
	STDMETHOD(AddOverlayDirtyRect)( LPRECT) ;
	STDMETHOD(Blt)( LPRECT, LPDIRECTDRAWSURFACE7, LPRECT, DWORD, LPDDBLTFX) ;
	STDMETHOD(BltBatch)( LPDDBLTBATCH, DWORD, DWORD) ;
	STDMETHOD(BltFast)( DWORD, DWORD, LPDIRECTDRAWSURFACE7, LPRECT, DWORD) ;
	STDMETHOD(DeleteAttachedSurface)( DWORD, LPDIRECTDRAWSURFACE7) ;
	STDMETHOD(EnumAttachedSurfaces)( LPVOID, LPDDENUMSURFACESCALLBACK7) ;
	STDMETHOD(EnumOverlayZOrders)( DWORD, LPVOID, LPDDENUMSURFACESCALLBACK7) ;
	STDMETHOD(Flip)( LPDIRECTDRAWSURFACE7, DWORD) ;
	STDMETHOD(GetAttachedSurface)( LPDDSCAPS2, LPDIRECTDRAWSURFACE7 FAR*) ;
	STDMETHOD(GetBltStatus)( DWORD) ;
	STDMETHOD(GetCaps)( LPDDSCAPS2) ;
	STDMETHOD(GetClipper)( LPDIRECTDRAWCLIPPER FAR*) ;
	STDMETHOD(GetColorKey)( DWORD, LPDDCOLORKEY) ;
	STDMETHOD(GetDC)( HDC FAR*) ;
	STDMETHOD(GetFlipStatus)( DWORD) ;
	STDMETHOD(GetOverlayPosition)( LPLONG, LPLONG) ;
	STDMETHOD(GetPalette)( LPDIRECTDRAWPALETTE FAR*) ;
	STDMETHOD(GetPixelFormat)( LPDDPIXELFORMAT) ;
	STDMETHOD(GetSurfaceDesc)( LPDDSURFACEDESC2) ;
	STDMETHOD(Initialize)( LPDIRECTDRAW, LPDDSURFACEDESC2) ;
	STDMETHOD(IsLost)() ;
	STDMETHOD(Lock)( LPRECT, LPDDSURFACEDESC2, DWORD, HANDLE) ;
	STDMETHOD(ReleaseDC)( HDC) ;
	STDMETHOD(Restore)() ;
	STDMETHOD(SetClipper)( LPDIRECTDRAWCLIPPER) ;
	STDMETHOD(SetColorKey)( DWORD, LPDDCOLORKEY) ;
	STDMETHOD(SetOverlayPosition)( LONG, LONG) ;
	STDMETHOD(SetPalette)( LPDIRECTDRAWPALETTE) ;
	STDMETHOD(Unlock)( LPRECT) ;
	STDMETHOD(UpdateOverlay)( LPRECT, LPDIRECTDRAWSURFACE7, LPRECT, DWORD, LPDDOVERLAYFX) ;
	STDMETHOD(UpdateOverlayDisplay)( DWORD) ;
	STDMETHOD(UpdateOverlayZOrder)( DWORD, LPDIRECTDRAWSURFACE7) ;
	STDMETHOD(GetDDInterface)( LPVOID FAR*) ;
	STDMETHOD(PageLock)( DWORD) ;
	STDMETHOD(PageUnlock)( DWORD) ;
	STDMETHOD(SetSurfaceDesc)( LPDDSURFACEDESC2, DWORD) ;
	STDMETHOD(SetPrivateData)( REFGUID, LPVOID, DWORD, DWORD) ;
	STDMETHOD(GetPrivateData)( REFGUID, LPVOID, LPDWORD) ;
	STDMETHOD(FreePrivateData)( REFGUID) ;
	STDMETHOD(GetUniquenessValue)( LPDWORD) ;
	STDMETHOD(ChangeUniquenessValue)() ;
	STDMETHOD(SetPriority)( DWORD) ;
	STDMETHOD(GetPriority)( LPDWORD) ;
	STDMETHOD(SetLOD)( DWORD) ;
	STDMETHOD(GetLOD)( LPDWORD) ;
};
